#!/usr/bin/env bash
# Generate scrape targets, FortiGate auth, and SD-WAN rules from .env (+ local maps).
# Sensible values live only in .env / gitignored files — never in committed YAML.
set -euo pipefail
cd "$(dirname "$0")"

if [[ ! -f .env ]]; then
  echo "missing .env — copy from .env.example" >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

mkdir -p fortigate prometheus/file_sd prometheus/rules

SSS_PACS_HOST="${SSS_PACS_HOST:-}"
SSS_PACS_DICOM_PORT="${SSS_PACS_DICOM_PORT:-11112}"
SSS_FORTIGATE_URL="${SSS_FORTIGATE_URL:-}"
SSS_FORTIGATE_TOKEN="${SSS_FORTIGATE_TOKEN:-}"

# --- PACS host blackbox targets (ICMP + DICOM TCP) ---
if [[ -n "$SSS_PACS_HOST" ]]; then
  cat > prometheus/file_sd/sss-pacs-icmp.yml <<EOF
- targets:
    - "${SSS_PACS_HOST}"
  labels:
    location: central
    system: sss-pacs
    check: icmp
EOF
  cat > prometheus/file_sd/sss-pacs-dicom.yml <<EOF
- targets:
    - "${SSS_PACS_HOST}:${SSS_PACS_DICOM_PORT}"
  labels:
    location: central
    system: sss-pacs
    check: dicom-tcp
EOF
  echo "wrote prometheus/file_sd/sss-pacs-icmp.yml and sss-pacs-dicom.yml"
else
  cat > prometheus/file_sd/sss-pacs-icmp.yml <<'EOF'
[]
EOF
  cat > prometheus/file_sd/sss-pacs-dicom.yml <<'EOF'
[]
EOF
  echo "SSS_PACS_HOST unset — ICMP/DICOM scrape disabled (empty file_sd)"
fi

# --- FortiGate ---
if [[ -n "$SSS_FORTIGATE_URL" && -n "$SSS_FORTIGATE_TOKEN" ]]; then
  cat > fortigate/fortigate-key.yaml <<EOF
"${SSS_FORTIGATE_URL}":
  token: ${SSS_FORTIGATE_TOKEN}
  probes:
    include:
      - System/Status
      - VirtualWAN/HealthCheck
EOF
  cat > prometheus/file_sd/sss-fortigate.yml <<EOF
- targets:
    - "${SSS_FORTIGATE_URL}"
  labels:
    system: sss-pacs
    location: central
EOF
  echo "wrote fortigate/fortigate-key.yaml and prometheus/file_sd/sss-fortigate.yml"
else
  # Empty target list so Prometheus still starts without FortiGate configured.
  cat > fortigate/fortigate-key.yaml <<'EOF'
{}
EOF
  cat > prometheus/file_sd/sss-fortigate.yml <<'EOF'
[]
EOF
  echo "SSS_FORTIGATE_URL/TOKEN unset — FortiGate scrape disabled (empty file_sd)"
fi

# --- AET → SD-WAN map (local, gitignored) ---
MAP_FILE=fortigate/aet-healthcheck.yaml
MAP_EXAMPLE=fortigate/aet-healthcheck.yaml.example
if [[ ! -f "$MAP_FILE" ]]; then
  if [[ -f "$MAP_EXAMPLE" ]]; then
    cp "$MAP_EXAMPLE" "$MAP_FILE"
    echo "created $MAP_FILE from example — edit with real AET mappings"
  else
    : > "$MAP_FILE"
  fi
fi

RULES_FILE=prometheus/rules/sss-sdwan.yml

python3 - "$MAP_FILE" "$RULES_FILE" <<'PY'
import sys
from pathlib import Path

map_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])

# (aet, health_check, [iface1, iface2, ...])
entries: list[tuple[str, str, list[str]]] = []
if map_path.exists():
    for raw in map_path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        aet, rest = line.split(":", 1)
        aet = aet.strip()
        parts = [p.strip().strip("'\"") for p in rest.split(",") if p.strip().strip("'\"")]
        if not aet or not parts:
            continue
        hc, members = parts[0], parts[1:2] + parts[2:3]  # at most two members
        entries.append((aet, hc, members))

lines = [
    "# Generated by configure.sh — do not edit by hand",
    "groups:",
    "  - name: sss_sdwan",
    "    interval: 1m",
    "    rules:",
]
if not entries:
    lines.append("      []")
else:
    for aet, hc, members in entries:
        lines.extend(
            [
                "      - record: sss_pacs_sdwan_up",
                "        expr: |",
                f'          max(fortigate_virtual_wan_status{{sla="{hc}",state="up"}}) or vector(0)',
                "        labels:",
                f'          aet: "{aet}"',
            ]
        )
        for idx, iface in enumerate(members, start=1):
            lines.extend(
                [
                    "      - record: sss_pacs_sdwan_member_up",
                    "        expr: |",
                    f'          max(fortigate_virtual_wan_status{{sla="{hc}",interface="{iface}",state="up"}}) or vector(0)',
                    "        labels:",
                    f'          aet: "{aet}"',
                    f'          slot: "{idx}"',
                    f'          interface: "{iface}"',
                ]
            )

out_path.write_text("\n".join(lines) + "\n")
n_members = sum(len(m) for _, _, m in entries)
print(f"wrote {out_path} ({len(entries)} AET mappings, {n_members} member rules)")
PY
